// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdgrX2dPZkw7OEXsX4Ds_5eY3NJPIzMBg',
    appId: '1:650511405970:web:2a81c385be946b99a8674b',
    messagingSenderId: '650511405970',
    projectId: 'flutterstop-f7046',
    authDomain: 'flutterstop-f7046.firebaseapp.com',
    storageBucket: 'flutterstop-f7046.firebasestorage.app',
    measurementId: 'G-L6V0JPS0CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJXPlyBiv4Xyk165UFl2LAKYfLarBJAA',
    appId: '1:650511405970:android:7bb470746385d4c4a8674b',
    messagingSenderId: '650511405970',
    projectId: 'flutterstop-f7046',
    storageBucket: 'flutterstop-f7046.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB46jDQamGVcm6lcUJ881wcFmvWFbF4d9Y',
    appId: '1:650511405970:ios:012a9e6eb3a35bc0a8674b',
    messagingSenderId: '650511405970',
    projectId: 'flutterstop-f7046',
    storageBucket: 'flutterstop-f7046.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB46jDQamGVcm6lcUJ881wcFmvWFbF4d9Y',
    appId: '1:650511405970:ios:012a9e6eb3a35bc0a8674b',
    messagingSenderId: '650511405970',
    projectId: 'flutterstop-f7046',
    storageBucket: 'flutterstop-f7046.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdgrX2dPZkw7OEXsX4Ds_5eY3NJPIzMBg',
    appId: '1:650511405970:web:fdd326884766d8d4a8674b',
    messagingSenderId: '650511405970',
    projectId: 'flutterstop-f7046',
    authDomain: 'flutterstop-f7046.firebaseapp.com',
    storageBucket: 'flutterstop-f7046.firebasestorage.app',
    measurementId: 'G-55XEPDC9E8',
  );

}